export const ADD_HEADER_ITEM = 'ADD_HEADER_ITEM';

export const ADD_NEW_POST_START = 'ADD_NEW_POST_START';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';
export const ADD_ANIMATE_SCS_ERR_BTN = 'ADD_ANIMATE_SCS_ERR_BTN';
export const ADD_NEW_POST_CONTAINER = 'ADD_NEW_POST_CONTAINER';

export const ADD_NEW_PRZEPISY_CONTAINER_START = 'ADD_NEW_PRZEPISY_CONTAINER_START';
export const ADD_NEW_PRZEPISY_CONTAINER_SUCCESS = 'ADD_NEW_PRZEPISY_CONTAINER_SUCCESS';
export const ADD_NEW_PRZEPISY_CONTAINER_FAIL = 'ADD_NEW_PRZEPISY_CONTAINER_FAIL';
export const ADD_NEW_PRZEPISY_CONTAINER = 'ADD_NEW_PRZEPISY_CONTAINER';

export const UPDATE_POST_DATA = 'UPDATE_POST_DATA';

export const FETCH_MAIN_CONTENT_START = 'FETCH_MAIN_CONTENT_START';
export const FETCH_MAIN_CONTENT_SUCCESS = 'FETCH_MAIN_CONTENT_SUCCESS';
export const FETCH_MAIN_CONTENT_FAIL = 'FETCH_MAIN_CONTENT_FAIL';

export const FETCH_PRZEPISY_SUCCESS = 'FETCH_PRZEPISY_SUCCESS';

export const FETCH_COMENT_SUCCESS = 'FETCH_COMENT_SUCCESS';

export const FETCH_TEXT_SUCCESS = 'FETCH_TEXT_SUCCESS';

export const FETCH_POST_CONTENT_START = 'FETCH_POST_CONTENT_START';
export const FETCH_POST_CONTENT_SUCCESS = 'FETCH_POST_CONTENT_SUCCESS';
export const FETCH_POST_CONTENT_FAIL = 'FETCH_POST_CONTENT_FAIL';
export const FETCH_POST_URL_LIST = 'FETCH_POST_URL_LIST';

export const CHECK_FORM_IS_VALID = 'CHECK_FORM_IS_VALID';
export const CHECK_PAY = 'CHECK_PAY';


export const CREATE_MAIN_CONTENT_VARIABLE = 'CREATE_MAIN_CONTENT_VARIABLE';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SN = 'AUTH_USER_SN';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_STATE_SUCCESS = 'AUTH_STATE_SUCCESS';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';